# Colorectal Cases

## Preop

ADULT SURG Colorectal ERAS MPP Hill This is what has all of the main ERAS components. Tylenol, gabapentin, Decadron, Alvimopan and heparin are all given in pre-op holding

ADULT STANDING Antimicrobial colorectal In general, I will give Ancef to patients with almost all patients with allergies to PCN. They have to remember the “severe” reaction. If it is a severe reaction, please use the second line antibiotics listed in the power plan.

Type and Screen are not typically needed for colectomy. They will have an antibody screen from office. If antibodies present, then d/w attending

Entereg for all colorectal patients (if they are not taking preoperative opoids)

VTE prophylaxix

Carbohydrate load (2 hours preop)

## Intraop

Positioning: Attending will typically position patients personally

Right sided=supine; Left sided=lithotomy; All laparoscopic colon cases will have their arms tucked with a chest tape strap.

NG/OG tubes: usually not needed, unless there is gastric distension. Patients receive multiple oral medicatinos in preop.

Review anesthesia fluid management during time out. 2L max volume, urine output not an accurate indicator.

Open procedures: No Epidural

## Postop

Fluids: Goal of 3 liters total in first 24 hours

**Postop Day 0**

- Goal-directed fluid administration
- OOB (Dangling not compliant)
- Diet
- Low Residue diet
- Ensure Supplements
- Teaching
  - Gum, Mag & Entereg
- Pain Management
  - PCA
  - Tylenol 1gm q6 ATC
  - Gabapentin 300mg TID
  - Tramadol PRN

Resume all baseline pain meds

Resume all home medications

No therapeutic anti-coagulation

Diabetes medicines
- Prefer to resume all oral diabetes meds
- Sliding-scale insulin ordered for all diabetics

**Postop Day 1**

Labs: K+ and CBC only

Heparin lock IV

Remove Foley

d/c PCA (unless open incision)

Out of bed > 6 hrs

Diet: low residue

Pain management

d/c PCA

Tylenol

Gabapentin 300 tid

Tramadol

Home meds

Oxy if lots of pain

Afternoon rounds

Check patient 2-4PM

Ambulation 2x’s by PM

Patient education

**Postop Day 2**

- No IV fluids unless indicated
- No labs unless indicated
- OOB >6 hrs
- No PT unless going to rehab or SNF (ask Hill first)
- Pain management: same as POD#1

Discharge planning

Consider early D/C (median LOS=2d)

Otherwise plan

Patient

Nursing

Afternoon rounds

Possible home today!

Check patient 2-3PM

Ambulation 2x’s by PM

Check for dehydration

Patient education

Give estimated date of discharge

**Postop Day 3-5**

- IVF
  - Consider bolus of IV fluids
  - Consider maintenance IV if we feel won’t resolve soon
- Labs 
  - No labs unless indicated
  - Consider ordering QOD Chem7 if prolonged ileus
- OOB >6 hrs
  - No PT unless likely to go to rehab or SNIF (ask Hill first)
- Pain management: Same as POD#1
- Afternoon rounds
  - Possible home today!
  - Check patient 2-3PM

Ambulation 2x’s by PM

Check for dehydration

Patient education

Give estimated date of discharge


