# Esophagectomy Robot Ivor Lewis

## Preoperative evaluation

PET scan evaluted for extent of tumor, focusing on proximity to the carina.

CT scan evaluated for presence of replaced left hepatic artery.

## Preop Area

Heparin is held if epidural catheter is planned

Clip hair from abdomen and right chest, including right axilla.  Hair is clipped to base of pubis.

## Room Prep

Double-decker Back Table

EGD Cart (check w/ Salo regarding adult vs neonatal scope)

BK Ultrasound (with robotic probe AND either hockey stick or small T probe). Will need sterile ultrasound jelly.

Walter 'Long Arm' retractor

Bean Bag

Salo Positioning Cart:

-   Four black side-rail clamps
-   Four rectangular lateral positioners
-   Yassargil socket
-   Well-leg holder (used as an arm holder)

Critical supplies (chek prior to pt in room)

-   Stapler 25mm DSTXL
-   Orvil 25mm
-   Stapler 21mm DSTXL
-   Orvil 21mm

\newpage

**Anesthesia**

-   Dual-lumen ETT tube (taped to left)
-   Arterial line (left arm will be on arm board)
-   Anesthesia may place epidural in preop

## Abdominal Position

Supine on blue foam pad.

Foley catheter (with Criticor temp sensor)

Bovie pad

Lower-body Bair Hugger at level of thighs, followed by single blanket and Velcro strap

Hair clipped from abdomen, right chest, and right axilla.

Pre-existing jejunostomy

-   Prep into field
-   Remove any eschar at site
-   Secure to skin inferiorly with 0 silk

Velcro strap over thighs and over lateral positioners

**Prep**

Patient is positioned frog-leg for prep (and is returned to supine during draping). Chloroprep (2 sticks) of abdomen and lower chest up to the level of nipples (in case urgent chest tube needed). Particular attention to prepping as far as possible to the left lateral side and the right lateral side. Prep continues inferior to base of pubis. At the end of prep, bilateral groins are prepped. 

**Drape**

Transverse 1000 drape is placed at the base of the pubis. On either side, the drape proceeds inferior and lateral to include both groins.  Top gloves are changed.

Blue utility (paper) drape is placed transversely just above level of pubis.  While the abdominal skin incisions are being closed, 

1000 Drapes x4 in rectangular fashion with top of field 10cm above xiphoid and bottom at base of penis. Ioban strips (4") aound the periphery of the surgical field after the trauma drape. Laparoscopic cords (gas, light cord, camera) passed off. Suction irrigator brought off field.

### Time Out

Operation header on consent

**Time Out**

Review:

-   Consent
-   Comorbidities, including cardiopulmonary disease
-   Anticoagulation plan. If preoperative heparin was held for epidural, plans for timing of its administration. Circulator and anesthetist set alarms.
-   Prior abdominal or thoracic operations
-   Allergies
-   Blood
    -   Surgeon’s expectation of blood loss
    -   Availability of blood (type/screen vs type/cross).
    -   Blood product administration limitations, if any
-   Introduction by name and role
-   Co-surgeons: Confirm availability prior to incision
-   Operative plan
-   Request ICU bed in STICU

*Comorbidities:*

Cardiopulmonary disease. If echo, ejection fraction and aortic valve area (if abnormal)

Beta blockage: Note whether patient on home beta blockade and if so, whether home medication was taken the morning of surgery.

Anticipated Intraop Problems:

-   Possibility of tension left pneumothorax due to carbon dioxide entry into left chest during mediastinal dissection
-   Expectation of ventilatory difficulties due to carbon dioxide entry into the right chest Gastric mobilization – Greater Curvature

## Laparoscopy

Pneumoperitoneum established with Veress needle at left subcostal or inferior to umbilicus *or* modified Hasson approach. Abdominal entry with 5mm optical port at future location of Port #2 in mid-axillary line at level of umbilicus. Laparoscopy to look for peritoneal implants.

## Robotic ports

Port #3 8mm left mid-axillary line 3cm above level of umbilicus $\rightarrow$ camera.

hook \| monopolar scissors \| Extend vessel sealer.

Port #4 left anterior axillary line. 8mm port $\rightarrow$

Port #2 right mid-axillary line. Switch from 5mm to 12mm robotic stapler port. Place 'sleeper' 0 Vicryl figure-of-eight suture and secure with a hemostat.

Port #1 left anterior axillary line 8mm port $\rightarrow$ fenestrated bipolar

Assistant port 8mm port inferior to umbilicus.  Port #3 will be switched to this position for jejunostomy later in the case.

Nathanson liver retractor placed in midline using the 5mm optical port to create a tract. Nathanson held in place with Salo Endoscopic Bookwalter secured to bedrail just inferior to right armboard.

## Abdominal Phase

### Lesser Sac Dissection

Gastrohpeatic ligament divided.  Celiac axis evaluated for resectability.  Right crus dissected to ensure resectability.  Dissection carried anteriorly and left crural dissection begun. Dissection posterior to esophagus.

Central node dissection begun, including common hepatic, left gastric, celiac, and proximal splenic aftery nodes. If replaced left hepatic artery present, may require preservation of left gastric artery. Left gastric artery divided with clips. 

Posterior gastric dissection.  Dissection is carried posterior towards most superior short gastric arteries (as these can be difficult to approach from the greater curvature side).

## Distal Greater curvature Dissection

The right gastroepiploic artery is identified and the lesser sac entere to the left of midline.  Dissection proceeds to the patient's right. This may require shifting ports:

- Camera to Port 2
- Vessel sealer to Port 3
- Tip Up to Port 4

Right gastroepiploic artery carefully preserved and gatrocolic omentum incised. Dissection proceeds to right to mobilize colon off duodenum. Kocher maneuver performed and omental adhesions to gallbladder taken down.

## Proximal Greater Curvature Dissection

Instruments are returned to original positions and dissection proceeds proximally, preserving the left gastroepiploic artery near its orgin. Posterior dissection from the pancreas and splenic artery is performed, followed by division of short gastric vessels

## Mediastinal dissection

Penrose drain is placed around esophagus and secured with stapler or Weck clips. Dissection proceeds to level of inferior pulmonary veins. Penrose is tucked into the mediastinum.

## Pyloric Drainage - Pyloromyotimy (optional)

Pyloromyotomy is performed with camera in Port #2 and hook in Port #3 and Tip up in Port #4 (may need to move camera to midline)

## Pyloric Drainage - Pyloroplasty (optional)

Stay sutures of 2-0 silk are placed cephalad and caudad to pyorus.  Pyloric incision is made with hook cautery.  Defect is closed with 2-0 silk cut to 6" (have 2 sutures ready)

## Creation of Conduit

"Ruler" is created by making 1cm marks with black marker on Tip up. Tip up grasper place into Port #4. Robotic stapler is introduced into Port 2. Staple line starts ~5cm from pylorus.  First firing with Green (4.8mm) stapler load followed by Blue loads.  Conduit is created with goal of 3-4cm.  Assistant retracts fundus towards left upper quadrant. 

## Preparation of Conduit

Camera is moved to Port #2. Suture cut needle driver is introduced into Port 3 and Tip Up into Port 4. Conduit is sutured to specimen with multiple sutures of 2-0 silk (cut to 6"). Arm 4 is undocked and 19 Fr Blake drain is introduced through the port. The drain is sutured to specimen with 2-0 silk cut to 4" 

** JP1??**

## Preparation for Thoracic Phase

Once conduit has been constructed, confirm presence in room of bean bag, two pillows, and an extra OR bed for transition to lateral decubitus position. 

## Preparation for ICG

One vial of ICG is resuspended with 10mL of water. 5mL of the solution is brought onto the sterile field in a 5mL syringe, which is fitted with a 25Ga needle. The remainder of the ICG is given to Anesthesia for later (intravenous) use. 



## Jejunostomy

Camera is moved to midline (or Port 2) and Tip up into Port 3. Camera re-oriented to 30 degrees up.  Ligament of Treitz is identified and site for jejunostomy marked at 30cm with marking pen on a Prestige with 1 dot for selected site and 2 transverse marks distally.  3-0 Stratafix on RB-1 is introduced with a non-cutting needle driver into Port 3. Insufflation pressre reduced to Jejunum is sutured to abdominal wall starting at 10:00. Pursestring is run to 2:00 position and 16Ga needle from a 14Fr Cook Introducer kit passed through the abdominal wall into the bowel.  Insufflation of air confirms proper position.  J wire and 14FR dilator introduced and left in place. Pursestring continues around proposed site and then proceeds cephalad to provide a broader area of fixation between bowel and abdominal wall.  Tract is dilated with 18Fr dilator. 14Fr MIC jejunostomy (trimmed to 10cm) is introduced through 18Fr sheath and positioned within the bowel.  5mL of water in a slip-tip (non-Luer) 10ml syringe (from the Cook introducer kit) are instilled into the jejunostomy balloon.   

## Closure

Robot is disengaged and kept sterile.  Abdomen is desufflated and ports removed.  Port #2 site is closed by tying 0 Vicryl suture.  Port sites are closed with 4-0 Monocryl followed by Dermabond.

## ICG injection into groin.

While port sites are being closed, "loincloth" is removed and hockey stick or small T ultrasound transducer is brought onto the field. Under ultrasound guidance with sterile ultrasound jelly, ICG is injected into groin nodes. 

## Transition to Lateral position

Patient is transferred to a spare OR table and a bean bag placed. Patient is positioned lateral with tip of scapula at break in the table. Pillows are used under and between the knees. Arm is supported on a Well Leg Holder affixed to the left headrail with a Yassargil clamp.

Anastomosis The right chest is entered and the right lung reflected anterior with the paddle placed in the superior/anterior port. The gastric conduit is placed into the mediastinum by tucking it medially from the right pleura into the posterior mediastinum, in order to allow the conduit to take the most direct path from the hiatus to the proximal esophagus. Gentle superior tension is now applied to the conduit in order to eliminate redundancy. The paddle retractor is now moved from the anterior/inferior port to the anterior/superior 12mm port and the lung reflected anterior and inferior.

OrVil The OrVil device is now used to place a EEA anvil into the distal esophagus. In general, a 25mm size is selected, unless the patient has particularly small frame, in which case a 21mm size is used. Two stay sutures of 2-0 silk on RB-1 needles are placed in the center of the esophageal staple line 3mm apart. A Harmonic scalpel is used to divide the staple line. The OrVil device is passed through the mouth and is passed through the fenestration in the staple line. The anvil portion of the OrVil is oriented so that the rounded portion is placed against the roof of the mouth. The OrVil is guided into the hypopharynx by pulling on the the tube end of the device. As the anvil approaches the hypopharynx, the jaw is pulled forward to allow passage of the anvil.

The shaft of the anvil is brought through the esophageal staple line, and the tube disconnected from the anvil by cutting the blue sutures.

The superior end of the conduit is opened along the staple line and the DST XL stapler (matching the diameter of the OrVil) introduced through the Alexis device. The stapler shaft is placed into the open end of the gastric conduit and the conduit pulled over it (‘sock over shoe’). The stapler spike is brought out through the greater curvature. The anvil is grasped with a Maryland grasper placed through a superior 5mm port and the two components of the stapler are mated and the stapler tightened and fired. The knob of the stapler is rotated two turns counter-clockwise until a click is felt, at which time the anvil will flip. The stapler is withdrawn and the donuts examined and sent for pathologic exam.

The anastomosis is completed by firing a Echelon Medium-Thick (Gold) linear) across the conduit cephalad to the anastomosis. The excess conduit is sent for pathologic exam as ‘additional gastric margin.’

NG Tube A Covidien Salem Sump 18Fr nasogastric tube is passed by the anesthetist. A laparoscopic BK ultrasound is used to monitor the passage of the NG tube through the esophagus and into the gastric conduit. The NG tube is passed to the level that all for dots are outside the nose, with the 4th dot at the nares. The NG tube is secured with an AMT bridle.

Chest Tube A 28Fr Blake chest tube is placed through the anterior/inferior 12mm port and is positioned into the posterior mediastinum. JP2 is placed near the gastric conduit. The right lung is re-inflated.

Closure The stapler access port incision is closed with 0 Vicryl to approximate the serratus muscle. The incisions are closed with 4-0 Monocryl followed by Dermabond.
