# Esophagectomy Robot/VATS

## Preoperative evaluation

PET scan evaluated for extent of tumor, focusing on proximity to the carina.

CT scan evaluated for presence of replaced left hepatic artery.

## Preop Area

-   Heparin is held if epidural catheter is planned
-   Type/Screen
-   Clip hair from abdomen and right chest, including right axilla. Hair is clipped from bilateral groins

## Room Prep

-   Double-decker Back Table
-   EGD Cart (check w/ Salo regarding adult vs neonatal scope)
-   BK Ultrasound with sterile ultrasound jelly
    -   Laparoscopic probe AND
    -   hockey stick probe AND
    -   robotic probe

Walter 'Long Arm' retractor

Salo Positioning Cart:

-   Three black side-rail clamps
-   Two rectangular lateral positioners
-   One round lateral positioner
-   Yassargil socket
-   Well-leg holder (used as an arm holder)

Robotic Instruments:

-   Tip Up Grasper
-   Fenestrated bipolar Forceps (420205)
-   Hot Shears (Monopolar scissors) 470179
-   Extend vessel sealer (480322)
-   SutureCut Large Needle Driver (470296)
-   Medium-Large Clip Applier (420327)
-   Large Needle Driver (470006)
-   Permanent Cautery Hook (470183) (hold)
-   Cadiere Forceps (470049) hold

Critical supplies (check prior to pt in room)

-   Stapler 25mm DSTXL
-   Orvil 25mm
-   Stapler 21mm DSTXL
-   Orvil 21mm

Suture

-   Stratafix Spiral PDS 3-0 RB-1 needle 15cm

Supplies:

-   Micropuncture kit (from Anesthesia Workroom)
-   Gel Port available
-   14Fr Balloon Jejunostomy tube (8200-14)
-   14Fr Cook introducer kit
-   18Fr Dilator and peelaway sheath

\newpage

**Anesthesia**

-   Epidural placed in preop area
-   Dual-lumen ETT tube (taped to left)
-   Arterial line (left arm will be on arm board)
-   Heparin 5000U SQ 1-2 hours after epidural placed

## Abdominal Position

Supine on blue foam pad

Foley catheter

Bovie pad

Lower-body Bair Hugger at level of thighs, followed by single blanket and Velcro strap

Hair clipped from abdomen, bilateral groins, right chest, and right axilla.

Pre-existing jejunostomy

-   Prep into field
-   Remove any eschar at exit site
-   Secure to skin inferiorly with 0 silk

**Prep**

Chloroprep (2 sticks) of abdomen and lower chest up to the level of nipples (in case urgent chest tube needed). Particular attention to prepping as far as possible to the left lateral side and the right lateral side. Prep continues inferior to base of pubis. At the end of prep, bilateral groins are prepped.

**Drape**

Transverse 1000 drape is placed at the base of the pubis. On either side, the drape proceeds inferior and lateral to include both groins. Legs are returned to supine position and Velcro strap placed at thighs. Top gloves are changed.

Blue utility (paper) drape is placed transversely just above level of pubis. While the abdominal skin incisions are being closed, ICG will be injected into bilateral groins.

1000 Drapes x4 in rectangular fashion with top of field 10cm above xiphoid and bottom at base of penis. Ioban strips (4") aound the periphery of the surgical field after the trauma drape. Laparoscopic cords (CO2, light cord, camera) passed off. Suction irrigator brought off field.

### Time Out

Review:

-   Consent
-   Comorbidities, including cardiopulmonary disease
-   Anticoagulation plan. If preoperative heparin was held for epidural, plans for timing of its administration. Circulator and anesthetist set alarms.
-   Prior abdominal or thoracic operations
-   Allergies
-   Blood
    -   Surgeon’s expectation of blood loss
    -   Availability of blood (type/screen vs type/cross).
    -   Blood product administration limitations, if any
-   Introduction by name and role
-   Co-surgeons: Confirm availability prior to incision
-   Operative plan
-   Request ICU bed in STICU

*Comorbidities:*

Cardiopulmonary disease. If echo, ejection fraction and aortic valve area (if abnormal)

Beta blockade: Note whether patient on home beta blockade and if so, whether home medication was taken the morning of surgery.

Anticipated Intraop Problems:

-   Possibility of tension left pneumothorax due to carbon dioxide entry into left chest during mediastinal dissection
-   Expectation of ventilatory difficulties due to carbon dioxide entry into the right chest

## Laparoscopy

Pneumoperitoneum established with Veress needle at left subcostal or inferior to umbilicus *or* modified Hasson approach. Abdominal entry with 5mm optical port at future location of Port #2 in mid-clavicular line superior to umbilicus. Laparoscopy to look for peritoneal implants.

Ports:

1)  Z-thread optical port at site for Port #1 in R mid-axillary line 5cm superior to umbilicus
2)  RLQ assisting port (5mm)
3)  Lower midline assisting port (later will become Port 2A)
4)  LLQ assisting port (5mm)

Site for jejunostomy is selected 25cm from Treitz. 9" 2-0 silk suture is placed on anti-mesenteric aspect of jejunum and tied to itself. Abdominal wall site for jejunostomy is selected to be superior to ports 3 and 4. Site is marked with skin marker

Falciform suspended with 0 silk suture on Keith needle

Once site for jejunostomy marked, will placed ports 2,3,4. Port 4 is lateral at level of umbilicus. Port #3 is somewhat more inferior, to allow sewing jejunostomy. Port #2 in midline, inferior enough to allow

## Robotic ports

Port #1 left anterior axillary line 8mm port 2cm above umbilicus. $\rightarrow$ fenestrated bipolar

5mm asstant ports RLQ and LLQ

Assistant port 8mm port inferior to umbilicus. Port #3 will be switched to this position for jejunostomy later in the case.

(locate future site for jejunostomy)

Port #3 8mm left mid-axillary line at level of umbilicus $\rightarrow$ camera.

Port #4 left anterior axillary line. 8mm port $\rightarrow$ Tip Up

Port #2 right mid-clavicular line 2cm above umbilicus. Switch from 5mm to 12mm robotic stapler port. Place 'sleeper' 0 Vicryl figure-of-eight suture and secure with a hemostat.

(suspend falciform with 0 silk on Keith needle)

Nathanson liver retractor placed in midline using the 5mm optical port to create a tract. Nathanson held in place with Endoscopic Bookwalter secured to bedrail just inferior to right armboard.

Place loop of 0 silk to suspend superior side of pylorus

Bed positioned to 12 degrees reverse Trendelenberg and tipped to right 10 degrees

## Abdominal Phase

Robot docked: Anatomy: UPPER ABDOMINAL. Position: PATIENT RIGHT

+---------------------+---------------+-----------------+---------------+
| Arm 1               | Arm 2         | Arm 3           | Arm 4         |
+=====================+===============+=================+===============+
| Fenestrated Bipolar | Camera        | Synchroseal OR\ | Tip Up        |
|                     |               | Vessel Sealer   |               |
+---------------------+---------------+-----------------+---------------+

### Distal Greater Curve

The course of the right gastroepiploic artery is identified and the lesser sac entered to the left of midline. Dissection proceeds to the patient's right. Right gastroepiploic artery carefully preserved and gatrocolic omentum incised. Dissection proceeds to right to mobilize colon off duodenum. Kocher maneuver performed and omental adhesions to gallbladder taken down.

## Posterior Stomach

Posterior dissection elevating stomach. Divide posterior gastric arteries. Dissection plane up to fundus and to short gastrics.

### Lesser Sac Dissection

Gastrohpeatic ligament divided. Right gastric artery divided at 3rd arcade (approx 5cm from pylorus). Celiac axis evaluated for resectability. Right crus dissected to ensure resectability. Dissection carried anteriorly and left crural dissection begun. Dissection posterior to esophagus.

Penrose can be looped around body of stomach and used to retract stomach off central lymph nodes by traction to LLQ port site.

Central node dissection begun, including common hepatic, left gastric, celiac, and proximal splenic artery nodes. If replaced left hepatic artery present, may require preservation of left gastric artery. Left gastric artery divided with clips.

Posterior gastric dissection. Dissection is carried posterior towards most superior short gastric arteries (as these can be difficult to approach from the greater curvature side). (Penrose drain can be placed at this part of the operation)

## Proximal Greater Curve

+--------------+---------------------+--------------+---------------+
| Arm 1        | Arm 2               | Arm 3        | Arm 4         |
+==============+=====================+==============+===============+
| Tip Up       | Fenestrated Bipolar | Camera       | Synchroseal\  |
|              |                     |              | Vessel Sealer |
+--------------+---------------------+--------------+---------------+

Dissection proceeds proximally, dividing the left gastroepiploic artery near its orgin. Posterior dissection from the pancreas and splenic artery is performed, followed by division of short gastric vessels

## Mediastinal dissection

Penrose drain is placed around esophagus and secured with Weck clips. Dissection proceeds to level of inferior pulmonary veins. Penrose is tucked into the mediastinum. When Penrose is placed, confirm that heparin has been given.

## Pyloric Drainage - Pyloromyotomy

Stay sutures are placed superior and inferior with 2-0 Silk.  The cephalad suture is looped with the prior loop of 0 silk placed at the Nathanson site

+---------------------+---------------+-----------------+---------------+
| Arm 1               | Arm 2         | Arm 3           | Arm 4         |
+=====================+===============+=================+===============+
| Fenestrated Bipolar | Camera        | Scissors OR\    | Tip Up        |
|                     |               | Cadiere         |               |
+---------------------+---------------+-----------------+---------------+


Pyloromyotomy is performed with camera in Port #2 and scissors in Port #3 and Tip up in Port #4 (may need to move camera to midline)

## Pyloric Drainage - Pyloroplasty (optional)

Pyloric incision is made with scossors or hook cauterh. Defect is closed with 2-0 silk cut to 6" (have 2 sutures ready)

## Creation of Conduit

Tip up grasper placed into Port #4. Robotic stapler is introduced into Port 1. Staple line starts \~5cm from pylorus. First firing with Green (4.8mm) stapler load followed by Blue loads. Conduit is created with goal of 4cm. Assistant retracts cut edge of specimen towards right upper quadrant. Vicryl suture is placed 2cm above the start of the staple line (approximately 7cm from pylorus).

## Preparation for ICG

One vial of ICG is resuspended with 10mL of water. 5mL of the solution is brought onto the sterile field in a 5mL syringe, which is fitted with a 25Ga needle. The remainder of the ICG is given to Anesthesia for later (intravenous) use.

## Final dissection of mediastinum

Once conduit has been disconnected from specimen, additional dissection of mediastinum cam be performed. A penrose drain is tied around the esopahgus.  Once this is finished the penrose drain is pushed up into the mediastinum with the tails to the patient's right.

## Preparation of Conduit

+---------------------+-------------+-----------------------------------+-------------+
| Arm 1               | Arm 2A      | Arm 3                             | Arm 4       |
+=====================+=============+===================================+=============+
| Fenestrated Bipolar | Camera      | **SutureCut Large Needle Driver** | Tip Up      |
+---------------------+-------------+-----------------------------------+-------------+

If there is entry into the left pleaura, JP1 (19Fr) is brought in through LLQ 5mm port. This is frequently not necessary. Tip Up retracts left crus laterally and drain is placed in left pleura. All of the fluted portion is placed into the chest. The dot is left at the hiatus. 

Conduit is sutured to specimen with multiple sutures of 2-0 silk (cut to 6"). After conduit is sutured, arm 4 is removed and JP2 brought in through that port. JP2 is now sutured to the specimen.

Conduit is now evaluated with ICG and with robotic ultrasound

## Jejunostomy

+---------------------+----------------+-----------------------------------+-------------+
| Arm 1               | Arm 2          | Arm 2A                            | Arm 3       |
+=====================+================+===================================+=============+
| Fenestrated Bipolar | Camera (30 up) | **SutureCut Large Needle Driver** | Tip Up      |
+---------------------+----------------+-----------------------------------+-------------+

Prior suture on jejunum is identified and grasped with suture passer at the pre-marked site. Two passes are made with the suture passer similar to transfascial sutures on a Stoppa hernia repair. The 22Ga needle from a **micropuncture kit** is introduced through the pre-marked site to extend 1cm into the abdominal cavity. 3-0 Stratafix on RB-1 is introduced with a non-cutting needle driver into Port 3. Insufflation pressure reduced to 8m Hg. Jejunum is sutured to abdominal wall starting at 10:00. Pursestring is run to 2:00 position and the J wire from the micropuncture kit threaded into the small bowel. Correct placement within the bowel lumen is confirmed by rapid insufflation of air through the needle. The micropuncture dilator is next used, followed by the J wire from a 14Fr Cook introducer kit. The tract is dilate with a 14FR dilator followed by 18Fr dilator introduced and left in place. Pursestring continues around proposed site and then proceeds cephalad to provide a broader area of fixation between bowel and abdominal wall. Tract is dilated with 18Fr dilator. 14Fr MIC jejunostomy 8200-14 (trimmed to 10cm) is introduced through 18Fr sheath and positioned within the bowel. 5mL of water in a slip-tip (non-Luer) 10ml syringe (from the Cook introducer kit) are instilled into the jejunostomy balloon.

## Drains

Once jejunostomy in place, JP1 and JP2 are routed lateral to jejunostomy and brought out through Port #4 and the LLQ assisting port. Enough slack is left on JP2 so that its outside length approximates that of JP1.

## Closure

Robot is disengaged. Laparoscopic cords are placed in a basin on a ring stand to be reused for the thoracic portion.

Abdomen is desufflated and ports removed. Port #2 site is closed by tying 0 Vicryl suture. Port sites are closed with staples. A Red Rubber Robinson catheter (or 8Fr feeding tube) is placed through the Nathanson subxiphoid access site and covered with a Tegaderm. The RRR is used in case it is necessary to observe the transposition of the conduit from the abdomen.

## ICG injection into groin.

While port sites are being closed, "loincloth" is removed and hockey stick or small T ultrasound transducer is brought onto the field. Under ultrasound guidance with sterile ultrasound jelly, ICG is injected into groin nodes.

## Thoracic Phase

## Transition to Corkscrew Position

Patient's chest is rotated to the left. Rectangular positioner supports scapula. Circular positioner on Left side supports chest. Rectangular positioner along left greater trochanter. Right arm rests on pink foam pad on Well Leg Holder. Lower and upper body bair hugger used. Right arm is elevated for prep and lowered once drapes in place.

## Prep and drape

Chloroprep including axilla and proximal right arm. Prep should include all of abdomen. Drape axilla/upper arm with 1000 drape.

Two blue "U" drapes used, folowed by trauma drape (or Universal). JP drains are draped out of the abdominal field but ports 1,2,2A, AND 3 are prepped into teh field. Ioban strips around edges. Once Ioban in place, right arm is lowered

Laparoscopic instruments are kept sterile and may be returned to the field if pleural adhesions are encountered.

### Thoracoscopy

Table is tipped 10-15 degrees to the left. Gas pressure turned down to 8mmHg in preparation for the thoracic phase. A site for entry in to the left chest is selected just posterior to the tip of the scapula OR lateral to nipple. An incision is made here and a 5mm optical port with a 5mm 0 degree scope used to enter the chest. The chest is insufflated at 8mmHg of carbon dioxide, which helps to both copllapase the lung and depress the diaphragm. One 12mm port is placed just lateral to the diaphragmatic reflection. It is ciritcal to avoid injury to the diaphragm (and liver) with the inferior port placement. A mini-thoracotomy incision is placed along the mid-axillary line, frequently in the same interspace as the inferior/anterior 12mm port. The chest is entered just superior to the rib and the intercostal muscles divided with the LigaSure device to allow the ribs to separate. A narrow Deaver retractor is used to guage the space between the ribs, as the width of the retractor approximates the diameter of the 25mm stapler. A 5mm ‘U’ port is generally placed as high as possible midway between the scapular tip port and the anterior/superior 12mm port t0o the 4 right 5

## Thoracic Dissection

The 1688 "Green" scope is used to identify the course of the thoracic duct. If a disruption is found, the duct is mass ligated as low as possible with 3-0 Stratafix on RB-1 needle.

## Delivery of Conduit into chest

The conduit is delivered into the thorax. This is done using a laparoscopic grasper. Ensure staple line faces you (right side). The specimen is removed through the assistant port incision. Stomach is pulled into the chest until the **Vicryl marker suture** is seen.

Division of esophagus just above level of azygous vein. ICG can be administered intravenously to check perfusion. If there is any question about the length of the conduit, confirm the length of the conduit prior to division of the esophagus.

Penrose drain is recovered. Specimen is sent for frozen section with instructions to freeze proximal margin.

## Abdominal Exposure (optional)

If needed to monitor passage of conduit into chest, the abdomen is insufflated using the RRR placed in the sub-xiphoid port. Ports #1, #2, #3 are re-opened and Nathanson retractor replaced. Robotic camera used to monitor passage of conduit into chest.

## Preparation of conduit

The gastric conduit is placed into the mediastinum by tucking it medially from the right pleura into the posterior mediastinum, in order to allow the conduit to take the most direct path from the hiatus to the proximal esophagus. Gentle superior tension is now applied to the conduit in order to eliminate redundancy.

## Circular stapled anastomosis - Orvil

OrVil The OrVil device is now used to place a EEA anvil into the distal esophagus. In general, a 25mm size is selected, unless the patient has particularly small frame, in which case a 21mm size is used. Two stay sutures of 2-0 silk on RB-1 needles are placed in the center of the esophageal staple line 3mm apart. A Harmonic scalpel is used to divide the staple line. The OrVil device is passed through the mouth and is passed through the fenestration in the staple line. The anvil portion of the OrVil is oriented so that the rounded portion is placed against the roof of the mouth. The OrVil is guided into the hypopharynx by pulling on the the tube end of the device. As the anvil approaches the hypopharynx, the jaw is pulled forward to allow passage of the anvil.

The shaft of the anvil is brought through the esophageal staple line, and the tube disconnected from the anvil by cutting the blue sutures.

The superior end of the conduit is opened along the staple line and the DST XL stapler (matching the diameter of the OrVil) introduced through the Alexis device (Port #2). The stapler shaft is placed into the open end of the gastric conduit and the conduit pulled over it (‘sock over shoe’). The stapler spike is brought out through the greater curvature. The anvil is grasped with a Maryland grasper placed through a superior 5mm port and the two components of the stapler are mated and the stapler tightened and fired. The knob of the stapler is rotated two turns counter-clockwise until a click is felt, at which time the anvil will flip. The stapler is withdrawn and the donuts examined and sent for pathologic exam.

The anastomosis is completed by firing a 60mm Gold load across the conduit cephalad to the anastomosis. The excess conduit is retrieved through the Alexis port and sent for pathologic exam as ‘additional gastric margin.’

## NG Tube

A Covidien Salem Sump 18Fr nasogastric tube is passed by the anesthetist. A laparoscopic BK ultrasound is used to monitor the passage of the NG tube through the esophagus and into the gastric conduit. The NG tube is passed to the level that all for dots are outside the nose, with the 4th dot at the nares. The NG tube is secured with an AMT bridle.

## Chest Tube

A 28Fr Blake chest tube is placed through the anterior/inferior 12mm port and is positioned into the posterior mediastinum. JP2 is placed near the gastric conduit. The right lung is re-inflated.

## Closure

The stapler access port incision is closed with 0 Vicryl to approximate the serratus muscle. The incisions are closed with 4-0 Monocryl followed by Dermabond.

## Postoperative care

Admission to ICU. Epidural dosed.

Medications:

-   Protonix 40mg IV daily
-   Metoprolol 2.5mg IV q6h (may increase to 5mg)
-   Home antihypertensives held unless bp is still elevated after adequate beta blockade
-   No bowel regimen
-   Reglan 10mg IV q6 hours

Labs:

-   Daily drain amylase from JP2 starting POD#2
-   CBC every other day or daily if elevated above 12
-   BMP every other day
-   CMP on admission and POD #4

Tube feeds at 30mL/hour start with Osmolite 1.5. Tube feeds advanced 10mL q12 hours once flatus returns.

Intravenous fluid stopped once tube feeds advanced and free water started 240mL qid via jejunostomy.

POD #1 Out of bed to chair

Chest tube to water seal on POD2 if no air leak. Chest tube removed once output below 200mL/day

JP2 removed by POD#7 if patient is otherwise doing well.

Upper GI POD#2 *AND* able to stand for 10min *AND* output less than 400mL/day. If good emptying on upper GI $\rightarrow$ NG removed.

Modified Barium Swallow once NG tube removed. Initiation of liquids dependent upon MBS.

POD #5 Epidural catheter removed if not done prior. Foley catheter removed once epidural out. No Flomax to be administered via jejunostomy
