# Gastrectomy Postop

## Postoperative PPI

Proton-pump inhibitors have been shown to reduce risk of marginal ulceration but also are associated with increased risk of delayed gastric emptying after pancreaticoduodenectomy and gastric bypass.

There is a limited evidence base for duration of PPIs after gastrectomy.  The American Society for Metabolic and Bariatric surgery [@edwardsS1550] recommends at least 90 days of PPIs. A retrospective study found lower rate of marginal ulcer with 90 days of PPI after gastric bypass compared with 30 days.

## Nasogastric tubes

The duration of nasogastric tubes will be determined by the attending surgeon, operation performed, and NG output. Experience with advanced recovery protocols would suggest that prolonged nasogastric tube drainage is not only unnecessary but may slow recovery.

For Dr Salo's patients, an upper GI is generally performed on postoperative day 2 using Isovue through the nasogastric tube. The patient stands upright and gastric emptying is evaluated

## Drains

Drain amylase is monitored daily starting on the second day after surgery.