# Colectomy Postop

**Postop Day 0**

-   Goal-directed fluid administration
-   OOB (Dangling not compliant)
-   Diet
    -   Low Residue diet
    -   Ensure Supplements
-   Teaching
-   Gum, Mag & Entereg
-   Pain Management
    -   PCA
    -   Tylenol 1gm q6 ATC
    -   Gabapentin 300mg TID
    -   Tramadol PRN
    -   Resume all baseline pain meds
-   Home Medications
    -   Resume all home medications (write on postop 0 so it can be administered morning of POD1)
    -   No therapeutic anti-coagiation
    -   Diabetes medicines
        -   Prefer to resume all oral diabetes meds
        -   Sliding-scale insulin ordered for all diabetics

**Postop Day 1**

-   Labs: K+ and CBC only
-   Heparin lock IV
-   Remove Foley
-   d/c PCA (unless open incision)
-   Out of bed \> 6 hrs
-   Diet: low residue
-   Pain management
    1)  d/c PCA
    2)  Tylenol
    3)  Gabapentin 300 tid
    4)  Tramadol
    5)  Home meds
    6)  Oxy if lots of pain
-   Afternoon rounds

1)  Check patient 2-4PM
2)  Ambulation 2x’s by PM
3)  Patient education

**Postop Day 2**

-   No IV fluids unless indicated
-   No labs unless indicated
-   OOB \>6 hrs
-   No PT unless going to rehab or SNF (ask Hill first)
-   Pain management
    -   Same as POD#1
-   Discharge planning
    -   Consider early D/C (median LOS=2d)
-   Otherwise plan
    -   Patient
    -   Nursing
-   Afternoon rounds

1)  Possible home today!
2)  Check patient 2-3PM
3)  Ambulation 2x’s by PM
4)  Check for dehydration
5)  Patient education
6)  Give estimated date of discharge

**Postop Day 3-5**

-   IVF

    -   Consider bolus of IV fluids
    -   Consider maintenance IV if we feel won’t resolve soon

-   Labs

    -   No labs unless indicated
    -   Consider ordering QOD Chem7 if prolonged ileus
    -   OOB \>6 hrs
    -   No PT unless likely to go to rehab or SNIF (ask Hill first)

-   Pain management

    -   Same as POD#1

-   Afternoon rounds

    1)  Possible home today!
    2)  Check patient 2-3PM
    3)  Ambulation 2x’s by PM
    4)  Check for dehydration
    5)  Patient education
    6)  Give estimated date of discharge
