# Metastatic EsoCa {#eso_metastatic}

## Palliative radiation

Palliative radiation vs chemoradiation [@penniment114]

Radiation along favored over chemoradiation in the palliaitve setting [@penniment114]

## Chemoradiation vs chemotherapy in Stage IV

[@guttmann1131]

## Stents for malignant disease

[@vakil1791]

Review of guidelines 2010 Am Society GI [@sharma258]

## Perc Esophagostomy

Percutaneous transesophageal gastrostomy (PTEG) can be used as an alternative to nasogastric decompression, particularly in malignant obstruction.

Systematic review of 14 studies[@zhu262] 3 cases of PTEG for malignant obstruction, all placed under sedation. [@singal402] 10 patients treated with PTEG for malignant bowel obstruction. Time from placement to death median 15 days. Unlike venting gastrostomy, all patients required suction to maintain resolution of malignent bowel obstruction symptoms. [@selby306] 38 patients treated with perc transesophageal gastrostomy (PTEG) which was successful in 35/38. Mean catheter duration 61 days with 5/35 requiring tube exchanges. [@rotellini-coltvet1901]

17 patients treated with PTEG [@udomsawaengsup2314]

