# Locally Advanced EsoCa {#locally_advanced}

Tumors that are T2N^+^M0 or T3NxM0 are considered locally-advanced. The high rate of failure with surgery alone has led to development of adjunctive therapies.

## Trimodality Therapy {#trimodality}

Trimodality therapy consists of chemoradiation (chemoRT) followed by surgery. Between 2010 and early 2024, this approach was the standard of care for locally-advanced esophageal cancer. In 2024, the ESOPEC trial showed superior survival for *adenocarcinoma* with perioperative "sandwich" FLOT chemotherapy compared to chemoRT. For squamous cell carcinoma, trimodality therapy continues to be the standard of care.

CROSS trial randomized 364 patients with resectable esophageal and gastroesophageal junction tumors (75% adenocarcinoma) to neoadjuvant chemoradiation consisting of 4,140 cGy of radiation with concurrent carboplatin and paclitaxel or surgery alone.[@vanhagen2074] Clinical node-positive disease was present in 16%. Pathologic complete response was seen in 23% of adenocarcinoma and 49% of squamous cell carcinomas. Median overall survival was 49 months after trimodality vs 24 months after surgery alone (p=0.003). Survival at 5 years was 47% with trimodality vs 34% with surgery alone. Squamous cell carcinomas appeared to have particular benefit, with a hazard ratio of 0.42 for squamous cell vs 0.74 for adenocarcinoma. Median survival was improved for adenocarcinoma from 27.1 months to 43.2 months, but the median survival for squamous cell increased from 27.1months to 81.6 months for squamous cell. Rate of R0 resection was higher with chemoradiation (92% vs 69% p\<0.001) and local recurrence rates lower (14% vs 34% P\<0.001), and peritoneal recurrence lower (4% vs 14% P\<0.001). Despite the relatively low dose of radiation, in-field recurrences were less than 5%. The primary cause of failure was distant disease (31%) and local/regional failure (14%). Therapy was well-tolerated with 17% grade 3 toxicity.[@oppedijk385]

Ten-year followup of the CROSS trial [@eyck1995] showed that the primary benefit of CROSS regimen was in reducing local and loco-regional recurrences. There was no difference in isolated distant recurrence betwee the two arms.

Alternative to carboTaxol for chemoradiation is FOLFOX (SOG trial [@leichman4555])

Ongoing PROTECT trial compares FOLFOX to paclitaxel and carboplatin [@messager318]

See also [Definitive ChemoRT](#eso_dcrt)

## Neoadjuvant Chemo (adenocarcinoma)

ESOPEC Trial [@heoppner323] compared FLOT chemotherapy with CROSS chemoradiation for *adenocarcinoma* of the esophagus and found better survival with FLOT. FLOT resulted in superior 3-year survival (57% vs 51%). Pathologic CR rate 16.7% vs 10%. Grade 3 toxicity 58% vs 50%. 90-day mortality 3.1% with FLOT vs 5.6% CROSS. pCR rate was much lower than original CROSS trial (23%). Notably, patients with an incomplete pathologic response after CROSS (90%) did not receive adjvant nivolumab, which has since become the standard of care due to the Checkmate 577 trial[@kelly1191].

POET Trial (Pre-Operative therapy in Esophageal adenocarcinoma Trial) treated 119 patients with adenocarcinoma of the gastroesophageal junction with either neoadjuvant chemotherapy (5-FU, leucovorin, cisplatin) followed by surgery or induction chemotherapy with the same agents, followed by chemoradiation (4000cGy with concurrent cisplatin and etoposide). The study suffered from slow accrual, but there was a suggestion of improved 3-year survival with preoperative chemoradiation (47.4% vs 27.7% *p*=0.07) as well as better local control (76.5% vs 59%). In addition, chemoradiation was associated with a higher pathologic complete response rate (15.6% vs 2%)[@stahl851].

Neo-AEGIS Trial [@reynolds401] Randomized patients with GE junction adenocarcinomas to CROSS vs modified MAGIC (prior to 2018) or FLOT (after 2018). Trial included Siewert I, II, and III tumors. Trial was underpowered and did not show a difference between the regimens.

OEO2 clinical trial [@allum5062] Randomized trial of preoperative chemotherapy with ECF for esophageal and GE junction cancers. Improved survival with preoperative chemotherapy. 

### Neoadjuvant Chemotherapy $\rightarrow$ ChemoRT

TOPGEAR study [@leong2252] randomized patients with gastric or GE junction adenocarcinoma to neoadjuvant chemo (ECF or FLOT) vs neoadjuvant chemo followed by chemoRT (4500cGy). Higher pCR rate with chemo $\rightarrow$ chemoRT (17% vs 8%) but no difference in survival at 67mo followup. Higher R0 resection rate with chemo $\rightarrow$ chemoRT (92% vs 88%) ECF used for 2/3 of patients and FLOT for 1/3.

German trial [@stahl851] randomized patients to preoperative chemotherapy (A) vs preoperative chemotherapy followed by preoperative chemoradiation (B). Higher pcR rate in arm B (15.6% vs 2%) and ypN0 resection (64.4% vs 37.7%).

## Postoperative chemoradiation

Intergroup-0116 [@macdonald725] [@smalley2327] treated 556 patients with adenocarcinoma of the stomach or GE junction with surgery along vs surgery followed by postoperative chemoradiation. After a median followup of over 5 years, median overall survival iin the surgery alone group was 27 months vs 36 months in the postoperative chemoradiation group (p=0.005) Decrease in local failure as the first site of failure in the chemoradiation group (19% versus 29%).

Chemoradiation after resection of GE junction tumors [@kofoed26] among a group of 211 patients with GE junction adenocarcinoma with positive lymph nodes with improved 3-year disease-free survival (37% vs 24%).

## Restaging

PET is routinely done for restaging esophageal cancer after chemoradiation. Interval metastasis is found in 9% of cases [@noordman965]. Similar findings in a European multicenteral study [@vanderzijden7759]

## Active Surveillance

Patients treated with neoadjuvant therapy who have a robust clinical response (as evidenced by PET and EGD) can be treated with intensive surveillance.

EGD is poor predictor of pCR due to low sensitivity[@sarkaria764]

## GE Junction

[@siewert260]
