# Superficial EsoCa (T1) {#superficial}

Superficial esophageal cancer is usually asymptomatic, which means that the diagnosis is generally made in the context of surveillance for Barrett's esophagus.

Nodular Barrett's esophagus can be best evaluated with endoscopic mucosal resection, which can provide further staging information if an adenocarcinoma is found, such as depth of invasion, differentiation, and lymphovascular invasion.

Larger lesions arising within Barrett's esophagus should first be evaluated with endoscopic ultrasound (EUS)

EUS is less sensitive for T1 lesions [@bergeron765] -\> use EMR for diagnosis [@maish1777]

T1a tumors have a low risk of nodal metastasis [@dunbar850]

## Endscopic Mucosal Resection (EMR) {#emr}

For patients with nodular Barrett's esophagus or small tumors judged to be T1 by endoscopic ultrasound, endoscopic mucosal resection (EMR) can be diagnostic and potentially curative.

EMR is likely sufficient for small tumors with favorable pathologic factors[@nurkin1090]:

- Size less than 2cm
- Lateral and deep margins clear
- Absence of lymphovascular invasion
- Well- or moderately- differentiated

Need for RFA of Barrett's after EMR: [@haidry87]

Combination therapy with EMR and RFA results in lower rate of recurrence than EMR alone.[@pech1200] 1000 patients with T1a adenocarcinoma werer treated with EMR followed by RFA with only 2 (0.2%) of patient dying of esophageal cancer with median followup of almost 5 years.[@pech652]

Review of EMR: [@soetikno4490] <!---JCO 2005--->

## Endoscopic submucosal dissection (ESD). {#esd}

For T1a tumors, EMR and ESD appear to have similar outcomes [@terheggen783] Terheggen, G. et al. A randomised trial of endoscopic submucosal dissection versus endoscopic mucosal resection for early Barrett’s neoplasia. Gut 66, 783–793 (2017).

Endoscopic submucosal dissection is a technique for deeper endoscopic removal of esophageal lesions using endoscopic cautery, which dissects through the submucosa. ESD has a higher rate of curative resection [@cao751] albeit at the cost of prolonged operative times and increased risk of complications such a bleeding. [@repici715]

ESD takes more time and has higher R0 resection rate but similar recurrence rate at 2 years [@terheggen783]

### Submucosal Adenocarcinoma (T1b)

NCCN: Low-risk T1b are size \<2cm, well or moderately-differentiated, no LVI, *and* depth of submucosal invasion \<500um

AATS expert consensus [@molena884] recommends esophagectomy for T1b tumors with any high-risk features

Netherlands [@grotnik109] 248 patients with T1b adenocarcinoma of the esophagus treated with EMR or surgery. Metastases were seen in 78 patients, and the 5-year cumulative incidence was 30.9 %. The risk of metastases increased with submucosal invasion depth (subdistribution hazard ratio \[SHR\] 1.08, for every increase of 500 μm), lymphovascular invasion (SHR 2.95), and for larger tumors (SHR 1.23, for every increase of 10 mm).

NCDB [@swanson693] A total of 3,157 patients met the inclusion criteria. Of these patients, 2,024 (64.1%) had cT1a and 1133 (35.9%) had cT1b disease. Among those with cT1b tumors, 649 (57.3%) underwent esophagectomy, 293 (25.9%) endoscopic resection, and 191 (16.8%) chemoradiotherapy. On unadjusted comparison, patients treated for esophageal adenocarcinoma with chemoradiotherapy had a lower rate of overall survival than those treated with endoscopic resection or esophagectomy (26.1% vs 73.1% vs 75.5%, P \< .001). On comparison of matched cohorts, patients undergoing endoscopic resection for cT1b tumors demonstrated lower rates of overall survival than those undergoing esophagectomy (60.6% vs 74.1%, P = .0013),
