# Locally-Advanced Gastric

Locally-advanced gastric cancer (T3 or N^+^) is generally treated with some form of adjuvant therapy, which has been shown to improve upon the outcomes with surgery alone.

## Preoperative Chemotherapy

**FLOT** chemotherapy [@al-batran1948] with 5FU, oxaliplatin and Taxotere superior for neoadjuvant chemotherapy compared with epirubicin, oxaliplatin and 5FU (MAGIC regimen).

Matterhorn trial evaluated the addition of anti-PD-L1 MAb **durvalumab** to FLOT for stage I-IVa adenocarcinoma of stomach and GE junction. Both groups received 4 cycles of FLOT every 15 days. Durvalumab group received 2 doses preop and 2 doses postop with FLOT in addition to 10 monthly doses of durvalumab. Surgery was performed 4-8 weeks after the last dose of chemotherapy. Longer disease-free survival and trend to longer overall survival with the addition of durvalumab without additional toxicity.[@janjigian217]

MAGIC study randomized 503 patients to perioperative 'sandwich' chemotherapy consisting of epirubicin, cisplatin, and 5-FU versus surgery alone. In the perioperative chemotherapy group, 4 cycles were administered prior to surgery, and 4 cycles afterwards. Tumors of the esophagus or gastroesophageal junction comprised 26% of the study population. While over 90% of patients assigned to the chemotherapy arm completed their preoperative chemotherapy, only 66% completed their postoperative therapy. Survival at 5 years was 36% in the perioperative chemotherapy group, compared with 24% in the surgery group (p\<0.001).[@cunningham11]

ACCORD-07 clinical trial [@ychou1715]: surgery +/- neoadjuvant cisplatin+5FU. Improved R0 resection rate but no difference in survival, perhaps due to poor accrual.

FFCD trial randomized patients to preoperative chemotherapy with 2 or 3 cycles of cisplatin and 5-FU versus surgery alone. Tumors of the lower esophagus or gastroesophageal junction comprised 75% of the study population. Survival at 5 years was longer in the chemotherapy group (38%) versus 24% in the surgery alone group (p=0.02).[@ychou1715]

RESONANCE-II trial of Oxaliplatin + S-1 (SOX) [@wang20]

## Postoperative chemotherapy

CLASSIC clinical trial randomized 1033 patients with stage II or III gastric cancer after D2 gastrectomy to 6 months of adjuvant chemotherapy with capecitabine and oxaliplatinversus vs surgery alone. Three-year survival was improved in the chemotherapy group (74% *v* 59%).[@bang315] [@noh1389]

## Postoperative chemoradiation

Intergroup 0116 trial [@macdonald725] [@smalley2327] Surgery +/- postoperative chemoradiation. Surgical quality control was poor, as 90% were treated a limited (R1) lymph node dissection. Long-term followup, however [@smalley2327] showed a persistent benefit of postoperative chemoradiation.

ARTIST trial 450 patients treated with a D1 $\alpha$ gastrectomy were randomized to adjuvant capecitibine and cisplatin versus chemoradiation consisting of two cycles of capcitabine/oxaliplatin followed by chemoradiation followed by chemotherapy. Overall 3- year survival did not differ between groups (78.2% vs 74.2% p =0.86). A post-hoc analysis of patients with positive nodes showed a beneficial effect of chemoradiation (77.5% *v* 72.3% p=0.365).[@lee268]

CRITICS trial [@cats616] treated all patients with preoperative chemotherapy (ECF or CapeOx) followed by surgery. Postoperative patients were then randomized between additional chemotherapy versus chemoradiation. No difference in survival between groups.

CRITICS-II Trial [@slagter877] resectable gastric cancer randomized to neoadjuvant chemo (DOC x4) vs chemo (DOC x2) followed by ChemoRT (CROSS) vs ChemoRT (CROSS).

## Preoperative chemoradiation

RTOG 9904: Phase II trial of preoperative chemoradiation for gastric adenocarcinoma[@ajani3953]. Findings of pathologic complete response (pCR) in 20%.

TOPGEAR trial: neoajuvant chemotherapy $\pm$ subsequent radiation therapy: chemo+RT had better pCR rate (17% vs 8%). No survival difference between groups.[@leong2252]

## Preop Immunotherapy

NEONIPIGA trial: MSI-Hi gastric and GE junction cancers treated with neoadjuvant nivolumbab (6 cycles) and ipilumumab (2 cycles) over 12 weeks. Among 29 patients that underwent surgery, 59% pathologic complete response and all patients had R0 resection.[@andre288]

MSKCC: MSI-Hi GI cancers treated with dostarlimab. Clinic response rate: rectal 50/50 (100%), colon 28/33 (82%), gastric 8/14 (57%), GE junction 1/3 (33%), esophageadl 1/3 (0%) [@cercek2297]
