# Gastric GIST

## Genetics

-   Mutation of KIT receptor tyrosine kinase in 80%
    -   KIT exon 9 mutations have lower response rate to imatinib and shorter progression-free survival than exon 11 mutations (especially at dose of 400mg daily)
-   Mutation in PDGRFA receptor tyrosine kinase in 5-10%. Most mutations respond to imatinib except D842V (which may respond to avapritinib)
-   No mutation of KIT or PDGFRA in 10-15%. Most will have functional inactivation of SDH complex and evidenced by lack of SDHB on IHC. These patients should be tested for germline SDH mutations. These tumors tend to occur in the stomach in younger patients.

Tyrosine kinase inhibitors:

-   imatinib - first line therapy
-   Sunitinib treatment is indicated for patients with imatinib-resistant tumors or imatinib intolerance.
-   Regorafenib is indicated for patients with disease progression on imatinib or sunitinib.
-   Ripretinib is indicated for patients who have received prior treatment with 3 or more kinase inhibitors, including imatinib.

## Surgery

Surgical resection ideally involved a negative histologic margin.  A wide resection margin is not required, nor is lymph node dissection unless nodes are clinically involved. [@dematteo51]

## Positive margins after resection

ACOSOG working group [@mccarter53] studies 819 patients undergoing resection of GIST under Z9000 and Z9001 clinical trials. 72 patients (8.8%) had an R1 resection, of whom 21 had intraperitoneal rupture or bleed.  Factors associated with R1 resection included tumor size >10cm, rectum location, and tumor rupture. Disease recurrence in patients with R1 resections was primarily due to associated tumor rupture. There was no difference in recurrence-free survival for patients underoing R1 vs R0 resection.

Norweigan report [@holmebakk419] of 401 patients wtih GIST of whom 47had R1 resection and 52 with tumor recurrence. In patients without rupture, there was no difference in 5-year recurrence-free survival for R1 vs R0 resection. In multivariable analysis, tumor rupture but not R1 resection was associates with recurrence. 

