# Salo Clinic {#mie_postop}

## Clinic Notes

In most cases, a note will already have been started, so first check under the Notes tab.

If note exists, start a new note and use the template ".lcir"

At the "HPI\>\>" prompt, enter history of present illness:

#### Identifier:

-   67M presentation with iron-deficiency anemia. Usual weight 145#
-   73F presentation with 3 months of dysphagia to solids. Usual weight 181#. Weight at presentation 151#
-   44M presentation with 6 weeks of reflux symptoms. Usual weight 165#

Baseline (usual) weight is important for gastroesophageal cancer patients.

No narrative (this is not a creative writing workshop)

Avoid descriptors such as "pleasant" or "unfortunate"

#### Workup

> EGD April 14, 2024 by Dr Larry Pennington: Malignant appearing stricture at 40cm. Pathology (S24-345229) shows poorly-differentiated adenocarcinoma. EUS May 1, 2024 by Dr Andrew Dries. Staged as uT3 N1 PET May 15, 2024: Hypermetabolic lesion in the distal esophagus. No regional lymphadenopathy. No metastatic disease

Each paragraph contains one study: study -\> date -\> operator -\> findings

Pathology accession number is helpful for staff to track down outside path

#### Consult Visit

> GI Surgical Oncology consultation June 1, 2024. Taking only liquids. No odynophagia. Hand grip strength R: 31/30/29. ECOG 0. Weight 165#. Still smoking.

#### ECOG performance scale

-   0 Fully active, able to carry on all activities
-   1 Ambulatory can do light house work, office work
-   2 Ambulatory but can’t work up and about more than 50% of waking hours
-   3 Capable of only limited selfcare; confined to bed or chair more than 50% of waking hours
-   4 Completely disabled; cannot carry on any selfcare; totally confined to bed or chair

### Update Problem list {#problem_list}

Critical to update problem list for co-morbidities which would affect anesthetic/operative management.

Add details to problem list under "Overview"

### Cardiac

-   History of heart attack?

-   Coronary artery stent? When? Within the last 6mo?

-   Is patient on antiplatelet therapy? Which agents?

-   Date and location of most recent echocardiogram

    -   If aortic stenosis: Is valve area \<1cm\^2?

    -   If pulmonary hypertension: Peak pressures?

-   Date and location of stress test. Is there ischemia? Who is cardiologist?

### Pulmonary

-   Prior diagnosis of COPD? Dyspnea at rest? Dyspnea walking up one flight of stairs?\
    Has patient had recent pulmonary function tests? Is patient on steroids? History of prior lung surgery?

### GI

Prior abdominal surgery? Hernia repair: Prosthetic mesh? Laparoscopic vs open inguinal hernia repair Prior history of bariatric surgery?

### Endocrine

If diabetes: Is insulin required? How much? Steroid use?

### Renal

If kidney disease, what is baseline creatinine? Dialysis?

### Neurologic

History of Stroke? History of TIA? Carotid bruit on exam? History of dementia?\
Who manages finances? Who makes medical decisions?

### Physical Exam

Cardiopulmonary exam

-   Carotid Bruit?

-   Cervical Incision?

-   Cardiac murmur

-   Abdominal incisions - reconcile with past surgical history

### Assessment/Plan

Enter assessment/plan after "A/P" prompt Do not erase blue-shaded "Assessment Plan: No problem-specific assessment/plan found for this encounter *Briefly* summarize assessment/plan Dr Salo will add A/P and rationale/evidence base

## Return Visit Notes

Use notes template ".lcir" Select HPI text from prior note and use Copy Forward button

### Summarize Recent Surgery

-   Minimally-invasive esophagectomy July 2, 2024. Benign postoperative course. Discharged on 5 cartons of tube feeds and protein shakes. Pathology (CMCS24-004553): T3 N1 M0 1/26 nodes margins negative
-   Postop visit July 14, 2024: Doing well. Staples out. Advance diet. Metoprolol decreased to 25mg daily x 7days-\> stop.

***Sign notes and forward to Dr Salo***

## 
