project:
  type: book

book:
  title: "CMC GI Surgical Oncology Handbook"
  author: "Jonathan Salo MD"
  #date: "8/22/2024"
  repo-url: https://github.com/gisurgonc/handbook/
  repo-branch: main
  repo-actions: [edit, issue]
  reader-mode: true
  cover-image: giso241009.jpeg
  chapters:
    - index.qmd
    - part: "Inpatient Care"
      chapters: 
      - 01-cmc_inpatient.qmd
      - 01-pv_inpatient.qmd
      - 01-rounds.qmd
      - 01-notes.qmd
      - 01-consults.qmd
      - 01-phone.qmd
      - 01-phone_dept.qmd
      - 01-signout.qmd
      - 01-discharges.qmd
      - 01-students.qmd
    - part: "Preoperative Care"
      chapters: 
        - 11-preop_esophageal.qmd
        - 31-clinic_salo.qmd
        - 31-clinic_hill.qmd
    - part: "Operating Room"
      chapters:
      - 02-colorectal_hill.qmd
      - 02-cv_port_ij.qmd
      - 02-lap_jejunostomy.qmd
      - 02-lap_gastrostomy.qmd
      - 02-robot_STgastrectomy.qmd
      - 02-esophagectomy_one_stage.qmd
      - 02-esophagectomy_il_robot.qmd
      - 02-esophagectomy_il_robotVATS.qmd
    - part: "Postop Care"
      chapters:
      - 03-postop_colectomy.qmd
      - 03-postop_lar.qmd
      - 03-postop_apr.qmd
      - 03-postop_gastrectomy.qmd
      - 03-gastrostomy.qmd
      - 03-jejunostomy.qmd
      - 03-jejunostomy_diabetes.qmd
      - 03-icu_esophagectomy.qmd
      - 03-ward_esophagectomy.qmd
    - part: "Outpatient"
      chapters:
      - 31-outpt_jejunostomy.qmd
      - 31-outpt_esophagectomy.qmd
    - part: "Esophageal Cancer"
      chapters: 
      - 04-eso_overview.qmd
      - 04-eso_objectives.qmd
      - 04-eso_objectives_chief.qmd
      - 04-eso_staging.qmd
      - 04-eso_t0.qmd
      - 04-eso_t1.qmd
      - 04-eso_t2.qmd
      - 04-eso_t3.qmd
      - 04-eso_m1.qmd
      - 04-eso_dCRT.qmd
      - 04-eso_salvage.qmd
      - 04-eso_nutrition.qmd
      - 04-eso_surgery.qmd
      - 04-eso_survivorship.qmd
      - 04-eso_surveillance.qmd
    - part: "Gastric Cancer"
      chapters:
      - 05-gastric_overview.qmd
      - 05-gastrectomy.qmd
      - 05-gastric_CDH1.qmd
      - 05-gastric_GIST.qmd
      - 05-gastric_t3.qmd
      - 05-gastric_m1.qmd
    - part: "Colon Cancer"
      chapters:
      - 06-colectomy.qmd
    - part: "Rectal Cancer"
      chapters:
      - 07-rectal_staging.qmd
      - 07-rectal_surgery.qmd
      - 07-rectal_crt.qmd
    - part: "Anal Cancer"
      chapters: 
      - 08-anal_SCCA.qmd
    - part: "Sarcoma"
      chapters: 
      - 10-sarcoma.qmd
    - references.qmd

bibliography: zotero.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    #documentclass: scrbook

editor: visual

