project:
  type: book

book:
  title: "CMC GI Surgical Oncology"
  author: "Jonathan Salo MD"
  #date: "8/22/2024"
  chapters:
    - index.qmd
    - 01-cmc_inpatient.qmd
    - 01-pv_inpatient.qmd
    - 01-rounds.qmd
    - 01-notes.qmd
    - 01-signout.qmd
    - 01-discharges.qmd
    - references.qmd

bibliography: zotero.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

