project:
  type: book

book:
  title: "CMC GI Surgical Oncology Handbook"
  author: "Jonathan Salo MD"
  #date: "8/22/2024"
  repo-url: https://github.com/gisurgonc/handbook/
  repo-branch: main
  repo-actions: [edit, issue]
  reader-mode: true
  chapters:
    - index.qmd
    - part: "Clinical Care"
      chapters: 
      - 01-cmc_inpatient.qmd
      - 01-pv_inpatient.qmd
      - 01-rounds.qmd
      - 01-notes.qmd
      - 01-signout.qmd
      - 01-discharges.qmd
      - 01-students.qmd
      - 01-clinic_salo.qmd
    - part: "Operating Room"
      chapters:
      - 02-colorectal_hill.qmd
      - 02-cv_port_ij.qmd
      - 02-lap_jejunostomy.qmd
      - 02-lap_gastrostomy.qmd
      - 02-robot_STgastrectomy.qmd
      - 02-esophagectomy_one_stage.qmd
    - part: "Esophageal Cancer"
      chapters: 
      - 04-eso_overview.qmd
      - 04-eso_objectives.qmd
      - 04-eso_objectives_chief.qmd
      - 04-eso_staging.qmd
      - 04-eso_nutrition.qmd
      - 04-eso_surgery.qmd
    - part: "Gastric Cancer"
      chapters:
      - 05-gastric_CDH1.qmd
    - part: "Colon Cancer"
    - part: "Rectal Cancer"
    - part: "Anal Cancer"
    - part: "Sarcomda"
    - part: "Melanoma"
    - references.qmd

bibliography: zotero.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    #documentclass: scrbook

editor: visual

